### ISSUE TITLE
Compiling with profiling causes segfault on Windows

### ISSUE THREAD

**Issue by ndmitchell** [snoyberg/pantry#2]
I reproducibly get:

```
C:\Neil\stack>stack --version
Version 1.10.0, Git revision d1f0fde156245ddbb6656461f3f3531ea84488a2 (dirty) x86_64 hpack-0.31.1

C:\Neil\stack>stack build --executable-profiling
pantry-0.1.0.0: build (lib)
Log files have been written to: C:\Neil\stack\.stack-work\logs\
Progress 1/3

--  While building package pantry-0.1.0.0 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2.exe --builddir=.stack-work\dist\5c8418a7 build lib:pantry --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\Neil\stack\.stack-work\logs\pantry-0.1.0.0.log

    Preprocessing library for pantry-0.1.0.0..
    Building library for pantry-0.1.0.0..
    [11 of 18] Compiling Pantry.Storage
    ghc.EXE: ^^ Could not load 'pantryzm0zi1zi0zi0zmHYD9JmijLq14hlw77Kj2zzk_PantryziTypes_zdfPersistFieldSqlFileSizze1_closure', dependency unresolved. See top entry above.


    ByteCodeLink.lookupCE
    During interactive linking, GHCi couldn't find the following symbol:
      pantryzm0zi1zi0zi0zmHYD9JmijLq14hlw77Kj2zzk_PantryziTypes_zdfPersistFieldSqlFileSizze1_closure
    This may be due to you not asking GHCi to load extra object files,
    archives or DLLs needed by your current session.  Restart GHCi, specifying
    the missing library using the -L/path/to/object/dir and -lmissinglibname
    flags, or simply by naming the relevant files on the GHCi command line.
    Alternatively, this link failure might indicate a bug in GHCi.
    If you suspect the latter, please send a bug report to:
      glasgow-haskell-bugs@haskell.org
```

Seems `pantry` stops me being able to profile `stack` itself, which would be handy because I have `stack` taking 6s somewhere I think it should take < 1s.

**Comment by snoyberg** [comment]
The pantry used by Stack does not live in this repo, it lives in the Stack
repo. Two other things though:

- @qrilka has recently pushed some performance enhancements
- this is almost certainly a GHC bug, not a bug in pantry

**Comment by ndmitchell** [comment]
Agreed, probably a GHC bug. Shall I just leave it? Who if anyone should I tell?

**Comment by snoyberg** [comment]
In this case, I wouldn't worry about it too much. Most of the slowness can be diagnosed via the `--verbose` flag, in-depth profiling isn't really necessary yet. I'm not opposed to reporting upstream to GHC, but I'm not sure how likely it is for them to investigate a TH/Windows/huge dep chain bug like this.

**Comment by ndmitchell** [comment]
`--verbose` was my first port of call. I was trying to speed up `stack run hadrian` for the GHC build system, and it showed:

```
2019-02-07 17:10:13.057085: [debug] Start: getPackageFiles C:\Neil\ghc\2019-02-04\ghc\libraries\Cabal\Cabal\Cabal.cabal
2019-02-07 17:10:13.663359: [debug] Finished in 607ms: getPackageFiles C:\Neil\ghc\2019-02-04\ghc\libraries\Cabal\Cabal\Cabal.cabal
```

No idea how `getPackageFiles` takes 607ms. It doesn't get faster the second time around, so it doesn't seem like disk IO. My first finger-in-the-air guess was a large number of package files and suboptimal big-_O_. Profiling was my attempt to see where.

**Comment by snoyberg** [comment]
IME with Stack, these slowdowns are usually from doing too much I/O or
external process calls, not a CPU or memory bottleneck. That's why my gut
feeling is that profiling isn't that helpful. I usually throw in more log
messages at this point for debugging.

**Comment by ndmitchell** [comment]
Thanks for the tip, I'll give it a whirl! Closing this ticket, I think you're right that no one is going to enjoy this as a test case :)
